export { default as Navbar } from "../components/Navbar/Navbar";
export { default as Cryptocurrencies } from "../components/Cryptocurrencies/Cryptocurrencies";
export { default as CryptoDetails } from "../components/CryptoDetails/CryptoDetail";
export { default as News } from "../components/News/News";
export { default as Home } from "../components/Homepage/Home";
export { default as Nft } from "../components/NFT/NFT";
export { default as LineChart } from "../components/Linechart/LineChart";
export { default as Footer } from "../components/Footer/Footer";
// export { default as TableImage } from "../components/TableImage/TableImage";
export { default as MetaMask } from "../components/MetaMask/MetaMask";
